version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unturned
      POSTGRES_USER: postgres
    networks:
      - mynetwork

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - mynetwork
    ports:
      - "5050:80"

networks:
  mynetwork:
    driver: bridge
